export interface ResourceAction {
  id: string;
  context: 'resource_adjust';
  playerAction: string;
  isReasonable: boolean;
  narrative: string;
  resourceChanges: Partial<Record<'hp' | 'food' | 'sanity', number>>;
  itemsConsumed: string[];
  itemsGained: string[];
  karmaChange: number;
  companionEffect: string | null;
}

export const resourceActions: ResourceAction[] = [
  {
    id: 'r01',
    context: 'resource_adjust',
    playerAction: '用绷带治疗同伴',
    isReasonable: true,
    narrative: '你小心翼翼地为同伴清理伤口，用最后一卷绷带仔细包扎好。同伴咬着牙没有出声，但眼神里满是感激。',
    resourceChanges: { hp: 20 },
    itemsConsumed: ['绷带'],
    itemsGained: [],
    karmaChange: 5,
    companionEffect: '同伴生命值+20',
  },
  {
    id: 'r02',
    context: 'resource_adjust',
    playerAction: '把罐头分给大家',
    isReasonable: true,
    narrative: '你打开两个罐头，把食物平均分给每个人，虽然每人只有几口，但温热的食物让所有人的脸上都露出了久违的笑容。围坐在一起分享食物的时刻，让大家暂时忘记了外面那个被AI统治的世界。',
    resourceChanges: { sanity: 10 },
    itemsConsumed: ['罐头', '罐头'],
    itemsGained: [],
    karmaChange: 5,
    companionEffect: '理智+5（同伴感激）',
  },
  {
    id: 'r03',
    context: 'resource_adjust',
    playerAction: '拆零件做武器',
    isReasonable: true,
    narrative: '你蹲在地上，借着微弱的灯光把两组零件拆开重新组装，金属碰撞声在寂静的夜里格外清脆。最终你用弹簧和钢管拼出了一把简易武器，虽然粗糙但足以在近距离造成伤害。',
    resourceChanges: {},
    itemsConsumed: ['零件', '零件'],
    itemsGained: ['简易武器'],
    karmaChange: 0,
    companionEffect: null,
  },
  {
    id: 'r04',
    context: 'resource_adjust',
    playerAction: '用酒精消毒伤口',
    isReasonable: true,
    narrative: '你咬紧牙关，将酒精倒在发炎的伤口上，剧烈的刺痛让你差点叫出声来。几分钟后灼烧感逐渐消退，伤口周围的红肿明显减轻，感染的风险被暂时控制住了。',
    resourceChanges: { hp: 15 },
    itemsConsumed: ['酒精'],
    itemsGained: [],
    karmaChange: 0,
    companionEffect: null,
  },
  {
    id: 'r05',
    context: 'resource_adjust',
    playerAction: '把同伴赶走',
    isReasonable: false,
    narrative: '你冷冷地告诉同伴，物资不够两个人活下去，让对方自己想办法。同伴沉默了很久，最后一言不发地收拾了几样东西消失在黑暗中，临走时的眼神让你的心像被什么东西狠狠揪了一下。',
    resourceChanges: { sanity: -20 },
    itemsConsumed: [],
    itemsGained: [],
    karmaChange: -15,
    companionEffect: '同伴离队',
  },
  {
    id: 'r06',
    context: 'resource_adjust',
    playerAction: '吃生肉充饥',
    isReasonable: false,
    narrative: '饥饿战胜了理智，你撕下一块生肉塞进嘴里，腥膻的味道让胃一阵翻涌但你强忍着咽了下去。肚子暂时不叫了，但隐隐的腹痛让你担心接下来几个小时可能会很难熬。',
    resourceChanges: { food: 15, hp: -20 },
    itemsConsumed: ['生肉'],
    itemsGained: [],
    karmaChange: 0,
    companionEffect: null,
  },
  {
    id: 'r07',
    context: 'resource_adjust',
    playerAction: '烧废品取暖',
    isReasonable: true,
    narrative: '你把捡来的废纸板和碎木头堆在铁桶里点燃，橘红色的火光在墙壁上投下摇曳的影子。大家围坐在火堆旁，冻僵的手指慢慢恢复了知觉，这一刻的温暖弥足珍贵。',
    resourceChanges: { sanity: 5 },
    itemsConsumed: ['废品'],
    itemsGained: [],
    karmaChange: 0,
    companionEffect: null,
  },
  {
    id: 'r08',
    context: 'resource_adjust',
    playerAction: '偷偷藏食物不给同伴',
    isReasonable: false,
    narrative: '你趁同伴睡着，悄悄把一部分食物藏进了自己的背包夹层里。但你没注意到同伴其实只是闭着眼睛，第二天对方看你的眼神明显多了一层戒备和失望。',
    resourceChanges: {},
    itemsConsumed: [],
    itemsGained: [],
    karmaChange: -10,
    companionEffect: '理智-10（同伴寒心）',
  },
  {
    id: 'r09',
    context: 'resource_adjust',
    playerAction: '修理收音机',
    isReasonable: true,
    narrative: '你拆开收音机的外壳，更换了烧毁的电容，重新焊接了天线接口，手指被焊锡烫了好几个泡。当沙沙的电流声中突然传来一段模糊的人声广播时，你的心跳几乎停了一拍——那是人类抵抗军的加密频道。',
    resourceChanges: {},
    itemsConsumed: ['零件'],
    itemsGained: ['可用收音机'],
    karmaChange: 3,
    companionEffect: '理智+3（互相信赖）',
  },
  {
    id: 'r10',
    context: 'resource_adjust',
    playerAction: '用材料制作陷阱',
    isReasonable: true,
    narrative: '你用铁丝和弹簧设计了一个简易绊索陷阱，又在触发点绑上了几个空罐头作为警报。部署在营地入口后，至少今晚可以安心睡个觉，不用担心AI巡逻机器人的突然造访。',
    resourceChanges: {},
    itemsConsumed: ['铁丝', '弹簧'],
    itemsGained: ['简易陷阱'],
    karmaChange: 0,
    companionEffect: null,
  },
];
